[project]
name = "orders-svc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ramon", email = "ramon@jrzylab.xyz" }
]
requires-python = ">=3.13"
dependencies = [
    "asgi-correlation-id>=5.0.1",
    "asyncio>=4.0.0",
    "dotenv>=0.9.9",
    "fastapi[standard]>=0.141.1",
    "httpx2>=2.13.1",
    "psycopg[binary]>=3.3.6",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "pytest-mock>=3.16.0",
]

[project.scripts]
orders-svc = "orders_svc:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
filterwarnings = [
    "ignore:The anyio\\.abc\\.BlockingPortal alias is deprecated:DeprecationWarning",
]
